---
title: ""
output: html_document
---

## Introduction

Analysis using Benford's Law has been incorporated into this Shiny App to make the benford.analysis package tools easier to use. This application allows you test Benford's Law against a custom data to detect digit and number patterns could point to number invention, systematic frauds, errors, or biases in the data. 

## Assess comformity to Benford's Law
Benford’s Law provides the expected frequency of digits in certain types of tabulated data. The main idea is that formal statistical tests can help us to evaluate the conformity and reasonableness to judge general conformity to a Benford curve and also to identifies manifest deviations that deserve further review.

1. The first digit test
2. The first two digits test
3. The first three digits test
4. The last two digits test
5. The Mantissa Arc test

## Subset your data

Using the absolute difference (difference between actual and expected counts), the data can be sort by the statistic to select the data noncomform to a Benford curve. The suspicious groups are those with the leading digits have the greatest measure of absolute difference.
